### ISSUE TITLE
What do you think of using like BaseController for file?

### ISSUE THREAD

**Issue by dnson** [codeaholicguy/koajs-starter-kit#1]
I think it's easier to find the file name

**Comment by codeaholicguy** [comment]
@dnson do you mean the file name of `controllers/base.js` should be `BaseController.js`? If so, I think the current name is good to go because it's in `controllers` folder.

**Comment by dnson** [comment]
what about orderdetail? should it be order-detail?

**Comment by codeaholicguy** [comment]
@dnson it's all about the convention which you choose, this is just `starter-kit` and you can customize it for your need when you start your project 😄
